[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./deployments" }]
remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    '@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts',
    'solmate=lib/solmate/src',
    'forge-std=lib/forge-std/src',
    '@uniswap/v3-core=lib/v3-core',
    '@uniswap/v3-periphery=lib/v3-periphery',
    'aerodrome-contracts=lib/contracts/contracts',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
